### PR TITLE
v4.0.0 development

### LINKED ISSUE #8: Some keys not being read on Windows
On windows 7 64 bit running python 32, none of the function keys, arrow keys or mod keys are read.
So f1 doesn't even trigger anything, up arrow doesn't trigger anything and ctrl doesn't trigger anything.

### LINKED ISSUE #37: readchar.readchar() seems to return bytes instead of a string
The [documentation for `readchar`](https://github.com/magmax/python-readchar#readchar) states:

> Reads the next char from `stdin`, returning it as a string with length 1.

However, it appears to return a byte sequence:

example.py:
```
import readchar

print("Press a key")
pressed = readchar.readchar()

print(type(pressed))
```

Output:
```
$ python example.py
Press a key
<class 'bytes'>
```

This is using

```
$ pip show readchar
Name: readchar
Version: 2.0.1
Summary: Utilities to read single characters and key-strokes
Home-page: https://github.com/magmax/python-readchar
Author: Miguel Ángel García
Author-email: miguelangel.garcia@gmail.com
License: MIT
```

on Windows in a Git Bash prompt.

### LINKED ISSUE #42: Bad while loop pegging CPU on Windows
https://github.com/magmax/python-readchar/blob/master/readchar/readchar.py#L71

Nothing slowing this while loop is causing a CPU core to be pegged on Windows. Either removing `if msvcrt.kbhit()` or adding a `time.sleep(0.001)` (or similar) is necessary.

### LINKED ISSUE #44: Add LICENSE file to repo and sdist

### LINKED ISSUE #66: Windows: properly supporting special key (arrows, etc.)
## Problem:

On Windows special keystrokes are sent to all Programs as a combination of two characters. The first one being a `\x00` (or `\xe0`?).
This is reflected in the code by checking the first read byte `a` and then reading again into `b` if `a` meets this condition:

https://github.com/magmax/python-readchar/blob/549c17ac9fd93ec3ac0b3d75168066b46560aadf/readchar/readchar.py#L70-L71

Then the two characters are used to calculate a number and look that up in a lookup table to find the corresponding constant to return. 

However, this lookup table only has rows for `a`=224 and not for `a`=0, which is what my windows10 Version uses. This leads to all calculated values
being offset by 224 and resulting in a `KeyError` and returning `None`.

In #65, some values are corrected to match the calculations with `a`=0, but the rest is still left as is.

## Solution 1:

Add a second entry into the lookup table for every key, so that both calculation return valid results. 

Form my perspective this seems stupid, so heres a better solution:

## Solution 2:

Ignore `a` in the calculation. It is not needed anyway, as only the second byte `b` is actually relevant for the pressed key. Use the value of `b`
directly as keys.

This also makes it easier to maintain, as now the values listed in the sources can be used directly instead of having to do calculations every time. See Example below.

## Discussion:

Which solution should be implemented? I would be willing to provide a pull request for either one.

### Removing the while loop:

The `msvcrt.getch()` already blocks until the next keypress, so I believe the `while 1` could be removed. But I might be mistaken and miss an
important detail elsewhere. This would solve the need for #42/#56.

## Example:

```python
xlate_dict = {
    # for windows scan codes see:
    #   https://msdn.microsoft.com/en-us/library/aa299374
     1: "key.ESC",
    28: "key.ENTER",
    59: "key.F1",
    60: "key.F2",
    61: "key.F3",
    62: "key.F4",
    63: "key.F5",
    64: "key.F6",
    65: "key.F7",
    66: "key.F8",
    67: "key.F9",
    68: "key.F10",
    87: "key.F11",
    88: "key.F12",
    82: "key.INSERT",
    83: "key.SUPR",
    73: "key.PAGE_UP",
    81: "key.PAGE_DOWN",
    71: "key.HOME",
    79: "key.END",
    72: "key.UP",
    80: "key.DOWN",
    75: "key.LEFT",
    77: "key.RIGHT"
}

def readkey(getchar_fn=None):
    # Get a single character on Windows. if an extended key is pressed, the
    # Windows scan code is translated into a the unicode sequences readchar
    # expects (see key.py).

    ch = msvcrt.getch()
    if ch == b'\x00' or ch == b'\xe0':
        ch2 = msvcrt.getch()

        try:
            return xlate_dict[int.from_bytes(ch2, 'big')]
        except KeyError:
            return None
    else:
        return ch.decode()



if __name__ == '__main__': # -------------------------
    while True:
        print(readkey())
```

### LINKED ISSUE #80: Pls add support shift+tab
I want use shift tab in inquirer. But readchar not read this keyevent
```
    print("Press a key")
    key = readchar.readkey()
    print("Key is {0}".format(key.encode()))
>>>Press a key
>>>shift+tab
>>>Key is b'\t'
```

### PR DESCRIPTION
**Pull request by Cube707**
This is a continuation of #71. I just felt that it was justified to create a new clean issue.

## Motivation

As the current Version 3.0.5 has some big issues and the windows support has always been lacking, I took the time to restructure the complete library.

## Changes

The following changes have been made:

### Breaking changes

- the `readkey()` function now raises a `KeyboardInterupt` when `CTRL+C` is pressed. (but `readchar()` can still be used to capture it). This is more inline with the python philosophy (IMHO) and prevents developers from accidentally trapping their users with no option to stop the programm.

### fixes

- windows now returns strings instead of bytestrings, same as on linux
- windows now supports most special characters
- swaped LF and CR, as per #69
- windows actually returns CR on ENTER, so the ENTER variable now points to the appropriate existing variable
- `__all__` should return a list of strings
- f5-f12 had wrong codes on linux
- code coverage is much better now: [Coverage Status](https://coveralls.io/github/Cube707/python-readchar?branch=master)
- workflows: code coverage is now measued during the testing workflow and uploaded to coveralls.io

### removed

- removed python 2.7, 3.4, 3.5 and pypy support

### changed

- ~support for NON-BLOCKING behavior~ this is now removed as it has problems with the terminalsettings as pointed out in #73 and discussed in #62
- general cleanup of config and setup files
- bump precommit-hook versions
- simplyfied .yamellinter.yml
- since yamllint v1.27.0 there is a new option `new-lines: type: platform` that allows for platform independent linting. Added this.
- reworked the github actions
- workflows: updated the used github actions to `actions/checkout@v3` and `actions/setup-python@v4`

### added

- extensive testing for both windows and linux
- automated workflow that runs the test on both platforms
- more keycodes for windows
- add end-of-line-fixer to pre-commit
- #44
- mac OS and FreeBSD run the linux behavior (note in the README that they are not supported but should work)
- `SHIFT+TAB` support on Linux

## related

closes #80
resolves #78, resolves #46
closes #75
closes #66
closes #56, resolves #42
closes #44
fixes #37
closes #9, resolves #8 

closes magmax/python-inquirer#156
fixes magmax/python-inquirer#155
fixes magmax/python-inquirer#117
closes magmax/python-inquirer#113

closes Kamik423/cutie#26
closes Kamik423/cutie#23

### CODE REVIEW

**Comment by C0D3D3V** [comment]
Did you try to use the PyCharm terminal for example to debug the input test script? I got one report that the inputs do not work on windows using PyCharm. I myself did not test it, and I think there is also an issue open for the old version, so it is not very important that this works.

**Comment by Cube707** [comment]
No I only tested in Windows CMD terminal and Debian bash so far. Both while using VS code. I have never used PyCharm. But you right, there is already an issue: #51

**Comment by qianyun210603** [comment]
@Cube707 

Thanks a lot for notifying me in #64!

This version indeed solves issue 1 in #64 but unfortunately it doesn't fix issue 2 as per my test on my ovh server (running ubuntu). Below is my test script:
```python
import sys
sys.path.insert(0, r"/root/python-readchar-v4")
from threading import Thread
from queue import Queue
from typing import Callable, Dict
import time
import logging
import readchar

logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(module)s - %(message)s', level=logging.INFO,
)

running = False


class KeyBoardMonitor(object):

    def __init__(self, callbacks: Dict[str, Callable[[str], None]] = None, quit_symbol: str = 'q'):
        self.callbacks = callbacks if callbacks else {}
        self.quit_symbol = quit_symbol
        self.running = True
        self.queue = Queue()
        self.thread = Thread(name="keyboard monitoring", target=self._keyboard_monitor)

    def register_callback(self, order: str, callback: Callable[[str], None]) -> None:
        self.callbacks[order] = callback

    def unregister_callback(self, order):
        del self.callbacks[order]

    def start(self):
        self.thread.start()

    def stop(self):
        self.running = False

    def _keyboard_monitor(self):
        while self.running:
            ch = str(readchar.readchar())
            if ch in self.callbacks:
                self.callbacks[ch](ch)
            if ch == self.quit_symbol:
                self.running = False

def myprint(ch):
    print(ch, "entered")
    if ch == 'q':
        global running
        running = False


if __name__=="__main__":
    watchdog = KeyBoardMonitor(callbacks={'q': myprint, 'p': myprint})
    watchdog.start()
    running = True
    for _ in range(300):
        if not running:
            break
        time.sleep(1)
        logging.info(f"current_time: {time.time()}")
```
copy this into file and change the path in `sys.path.insert` to the "master" branch of local clone of your repo in r"/root/python-readchar-v4", I still see unwanted blanks (should come from the `\r` generated by `setraw` and missing linebreaks between logs:
image

In contrast, if using my version in pull request #64, I can get clean log outputs.
image

Would you please take some further look?

Thanks!

**Comment by Cube707** [comment]
@qianyun210603 please see https://github.com/Cube707/python-readchar/pull/5

Would you also be so kind and edit your comment shorter to keep this thread manageable and more on-topic. Its already big enough with all the commits and linked issues...

**Pull request closed without merging**
