### PR TITLE
include `py.typed` in package

### LINKED ISSUE #100: missing py.typed marker
mypy raises an error when importing readchar.

```
error: Skipping analyzing "readchar": module is installed, but missing library stubs or py.typed marker
```

Fix this issue by adding a py.typed marker:

https://peps.python.org/pep-0561/#packaging-type-information

Python Version: 3.10.6
mypy version: 0.991
readchar version: 4.0.3

### PR DESCRIPTION
**Pull request by Cube707**
this should enable mypy to analyse the package and fix #100

@phoenixr-codes can you please confirm this fixes the issue? Use this to install the pre-release version:

```bash
pip install -U --pre readchar==4.0.4.dev0
```

### CODE REVIEW

**Comment by phoenixr-codes** [comment]
This **does not** fix the issue for some reason - even after upgrading mypy and clearing the cache.

Following https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages, it might be neccessary to set `zip_safe` to `False`.

**Comment by Cube707** [comment]
hm, thats anoying. I will look into this some more...

**Comment by Cube707** [comment]
@phoenixr-codes it should work now, could you please try again? Use:

```bash
pip install -U --pre readchar==4.0.4.dev1
```

**Comment by Cube707** [comment]
But I lade sure that this time the gile is included 7n both the `.tar.gz` and the wheel, wird.

But thanks for the hints from other packages, I will look how they handle it

**Comment by Cube707** [comment]
Ok I found the problem. My release-pipeline is a bust and actually always releases `master`, so these changes are not in the pre-release versions...  -_-

If you have the time you could try installing directly from the repo, like this:

```bash
pip install -U git+https://github.com/magmax/python-readchar@v4.0.4-dev1
```

I will fix the pipeline...

**Comment by Cube707** [comment]
@phoenixr-codes The pipeline is fixed and the newest pre-release version now actually containes the changes (also in the versions pushed to pypi). So installing this should work:

```bash
pip install -U --pre readchar==4.0.4.dev1
```

**Pull request merged**
