### PR TITLE
support page up and page down

### PR DESCRIPTION
**Pull request by kcsaff**
Properly supports the page up & page down keys, as well as providing aliases for them & HOME, END.

### CODE REVIEW

**Comment by magmax** [comment]
Hello,

I've just fixed the problem with depenencies that was making the build to fail. What a hell.

Could you kindly merge master against your branch?

Thank you.

**Comment by kcsaff** [comment]
Travis seems to change their tooling relatively frequently, & it's tough to debug when you have to push to see if it works! :)

**Comment by kcsaff** [comment]
Anyways should be good to merge now if you want.

**Comment by magmax** [comment]
I will release this next week.

Thank you very much.

**Pull request merged**
